/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZonesRouteImport } from './routes/zones'
import { Route as EvaluationRouteImport } from './routes/evaluation'
import { Route as DataEntryRouteImport } from './routes/data-entry'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as AuditorRouteImport } from './routes/auditor'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArchiveIdRouteImport } from './routes/archive.$id'

const ZonesRoute = ZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationRoute = EvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const DataEntryRoute = DataEntryRouteImport.update({
  id: '/data-entry',
  path: '/data-entry',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditorRoute = AuditorRouteImport.update({
  id: '/auditor',
  path: '/auditor',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveIdRoute = ArchiveIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArchiveRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/auditor': typeof AuditorRoute
  '/checklist': typeof ChecklistRoute
  '/data-entry': typeof DataEntryRoute
  '/evaluation': typeof EvaluationRoute
  '/zones': typeof ZonesRoute
  '/archive/$id': typeof ArchiveIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/auditor': typeof AuditorRoute
  '/checklist': typeof ChecklistRoute
  '/data-entry': typeof DataEntryRoute
  '/evaluation': typeof EvaluationRoute
  '/zones': typeof ZonesRoute
  '/archive/$id': typeof ArchiveIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/auditor': typeof AuditorRoute
  '/checklist': typeof ChecklistRoute
  '/data-entry': typeof DataEntryRoute
  '/evaluation': typeof EvaluationRoute
  '/zones': typeof ZonesRoute
  '/archive/$id': typeof ArchiveIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/archive'
    | '/auditor'
    | '/checklist'
    | '/data-entry'
    | '/evaluation'
    | '/zones'
    | '/archive/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/archive'
    | '/auditor'
    | '/checklist'
    | '/data-entry'
    | '/evaluation'
    | '/zones'
    | '/archive/$id'
  id:
    | '__root__'
    | '/'
    | '/archive'
    | '/auditor'
    | '/checklist'
    | '/data-entry'
    | '/evaluation'
    | '/zones'
    | '/archive/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArchiveRoute: typeof ArchiveRouteWithChildren
  AuditorRoute: typeof AuditorRoute
  ChecklistRoute: typeof ChecklistRoute
  DataEntryRoute: typeof DataEntryRoute
  EvaluationRoute: typeof EvaluationRoute
  ZonesRoute: typeof ZonesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zones': {
      id: '/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-entry': {
      id: '/data-entry'
      path: '/data-entry'
      fullPath: '/data-entry'
      preLoaderRoute: typeof DataEntryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auditor': {
      id: '/auditor'
      path: '/auditor'
      fullPath: '/auditor'
      preLoaderRoute: typeof AuditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive/$id': {
      id: '/archive/$id'
      path: '/$id'
      fullPath: '/archive/$id'
      preLoaderRoute: typeof ArchiveIdRouteImport
      parentRoute: typeof ArchiveRoute
    }
  }
}

interface ArchiveRouteChildren {
  ArchiveIdRoute: typeof ArchiveIdRoute
}

const ArchiveRouteChildren: ArchiveRouteChildren = {
  ArchiveIdRoute: ArchiveIdRoute,
}

const ArchiveRouteWithChildren =
  ArchiveRoute._addFileChildren(ArchiveRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArchiveRoute: ArchiveRouteWithChildren,
  AuditorRoute: AuditorRoute,
  ChecklistRoute: ChecklistRoute,
  DataEntryRoute: DataEntryRoute,
  EvaluationRoute: EvaluationRoute,
  ZonesRoute: ZonesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
